FROM apache/spark:4.0.2
COPY jars/iceberg-aws-bundle-1.10.1.jar $SPARK_HOME/jars/iceberg-aws-bundle-1.10.1.jar
COPY jars/iceberg-spark-runtime-4.0_2.13-1.10.1.jar $SPARK_HOME/jars/iceberg-spark-runtime-4.0_2.13-1.10.1.jar
COPY jars/postgresql-42.7.11.jar $SPARK_HOME/jars/postgresql-42.7.11.jar