FROM apache/spark:4.1.2
COPY iceberg-aws-bundle-1.11.0.jar $SPARK_HOME/jars/iceberg-aws-bundle-1.11.0.jar
COPY iceberg-spark-runtime-4.1_2.13-1.11.0.jar $SPARK_HOME/jars/iceberg-spark-runtime-4.1_2.13-1.11.0.jar