services:
  spark-iceberg:
    build: spark-docker/.
    image: marq/spark
    container_name: spark-iceberg
    command: "tail -f /dev/null"
    depends_on:
      - seaweed-fs
      - metastore-service
    networks:
      - spark_net
    ports:
      - 7077:7077 # master endpoint
      - 8080:8080 # master ui
      - 8081:8081 # worker ui
      - 4040:4040 # job ui
    volumes:
      - ./spark-docker/conf:/opt/spark/conf

  metastore-service:
    build: hive-docker/.
    image: marq/hive
    container_name: metastore-serivce
    depends_on:
      - metastore-db
    networks:
        - spark_net
    environment:
      - SERVICE_NAME=metastore
      - DB_DRIVER=postgres
      - SERVICE_OPTS=-Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://metastore-db:5432/metastore -Djavax.jdo.option.ConnectionUserName=hive -Djavax.jdo.option.ConnectionPassword=password
    ports:
      - 9083:9083
    volumes:
      - metastore_data:/opt/hive/data/warehouse
    
  metastore-db:
    image: postgres:latest
    container_name: metastore-db
    restart: always
    networks:
      - spark_net
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: password
      POSTGRES_DB: metastore
    ports:
      - "5432:5432" # db endpoint
    volumes:
      - postgres_data:/var/lib/postgresql

  seaweed-fs:
    image: chrislusf/seaweedfs:latest
    container_name: seaweed-fs
    networks:
      - spark_net
    ports:
      - 9333:9333 # master ui
      - 23646:23646 # admin ui
      - 8333:8333 # aws endpoint
      - 8181:8181 # iceberg rest catalog
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=secret
      - S3_BUCKET=general-bucket
      - S3_TABLE_BUCKET=warehouse-bucket
    volumes:
      - seaweed_volume:/data

volumes:
  seaweed_volume:
  postgres_data:
  metastore_data:

networks:
  spark_net:
