spark.sql.extensions                                        org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.catalog.icicle                                    org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.icicle.type                               rest
spark.sql.catalog.icicle.uri                                http://seaweed-fs:8181
spark.sql.catalog.icicle.io-impl                            org.apache.iceberg.aws.s3.S3FileIO
spark.sql.catalog.icicle.warehouse                          s3://warehouse-bucket
spark.sql.catalog.icicle.s3.endpoint                        http://seaweed-fs:8333
spark.sql.catalog.icicle.rest.auth.type                     oauth2
spark.sql.catalog.icicle.oauth2-server-uri                  http://seaweed-fs:8181/v1/oauth/tokens
spark.sql.catalog.icicle.s3.path-style-access               true
spark.sql.catalog.icicle.s3.remote-signing-enabled          false
spark.sql.catalog.icicle.s3.signer.type                     false

spark.sql.catalogImplementation                             hive
spark.hadoop.hive.metastore.uris                            thrift://metastore-service:9083


### default credentials for example
## hive metastore connects to postgres with jdbc and spark connects to the hive metastore with thrift
# javax.jdo.option.ConnectionURL                              jdbc:postgres://metastore-db:5432/metastore
# javax.jdo.option.ConnectionUserName                         hive
# javax.jdo.option.ConnectionPassword                         password
# javax.jdo.option.ConnectionDriverName                       org.postgresql.Driver

## we connect to seaweedfs s3tables with a default admin
# spark.sql.catalog.icicle.credential                         admin:secret
# spark.sql.catalog.icicle.s3.access-key-id                   admin
# spark.sql.catalog.icicle.s3.secret-access-key               secret
# spark.sql.catalog.icicle.client.region                      us-east-1
# spark.sql.defaultCatalog                                    icicle